application: browser-issue-tracker-search
version: 2016-10-20
runtime: python27
threadsafe: true
api_version: 1

# default_expiration: "30s"

builtins:
- remote_api: on

libraries:
  - name: jinja2
    version: "2.6"
  - name: webapp2
    version: "2.5.2"

handlers:

# Static handlers ---------------------------------------------------------------
#- url: /favicon\.ico
#  static_files: static/img/chromium-128.png
#  upload: static/img/chromium-128\.png

- url: /css
  static_dir: css
  #expiration: 30s
  secure: always

- url: /img
  static_dir: img
  #expiration: 30s
  secure: always

- url: /js
  static_dir: js
  #expiration: 30s
  secure: always

- url: /deps.vulcanized.html
  static_files: deps.vulcanized.html
  upload: deps.vulcanized.html
  secure: always

- url: /deps.vulcanized.js
  static_files: deps.vulcanized.js
  upload: deps.vulcanized.js
  secure: always

#- url: /bower_components/polymer/polymer.html
#  static_files: bower_components/polymer/polymer.vulcanized.html
#  upload: bower_components/polymer/polymer.vulcanized.html
#  secure: always

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /cors
  script: main.app
  secure: always

- url: /devsite
  script: main.app
  secure: always

- url: /
  script: main.app
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.csv$
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.sql[3]$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.scss$
- ^(.*/)?node_modules
- ^(.*/)?tests
- ^(.*/)?.[LICENSE|PATENTS|AUTHORS|CONTRIBUTING|COPYING](\.md)?
- ^(.*/)?.*\.md$

- ^http2push/example
- ^http2push/site
- ^static/sass
- ^.*Makefile
- ^bower_components/url-search-params/template/.*
- bower_components/[^/]+/bower_components/.*$
- bower_components/(.+/)+(test/|demo/|README|AUTHORS|CONTRIBUTING|PATENTS|Makefile)
